#
# Module manifest for module 'OneLoginV2'
#
# Generated by: Joe Alcorn
#
# Generated on: 8/1/2021
#
@{
    ModuleVersion = '0.0.1'
    GUID = 'c750dc3b-6c28-4eef-9939-a9defbbeea0b'
    Author = 'Joe Alcorn'
    CompanyName = 'PLNU'
    Copyright = '(c) Joe Alcorn. All rights reserved.'
    Description = 'A module to interact with OneLogin''s V2 APIs'
    RootModule = 'OneLoginV2.psm1'
    RequiredModules = @(
        'Microsoft.PowerShell.SecretManagement'
        'Configuration'
    )
    #FunctionsToExport = '*'
    #CmdletsToExport = @()
    #VariablesToExport = '*'
    #AliasesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags = "OneLogin","REST"
            LicenseUri   = "https://github.com/joalcorn/OneLoginV2/blob/master/LICENSE"
            ProjectUri = "https://github.com/joalcorn/OneLoginV2"
            ReleaseNotes = ''
        } 
    }
}